version: '3.9'
services:
  postgres:
    image: postgres:16
    container_name: sales_etl_postgres
    environment:
      POSTGRES_DB: sales
      POSTGRES_USER: sales_user
      POSTGRES_PASSWORD: sales_password
    ports:
      - "5432:5432"
    volumes:
      - ./sql/init.sql:/docker-entrypoint-initdb.d/init.sql
      - postgres_data:/var/lib/postgresql/data
volumes:
  postgres_data:
